### ISSUE TITLE
Minor doubts and fixes

### ISSUE THREAD

**Issue by prateekrastogi** [inspectorioinc/docker-prediction-io#1]
Hi,

First of all, I would really like to thank you for open-sourcing docker-compose deployment of predictionio universal recommender. As a solo developer wanting to integrate universal recommender in his personal project and tired after trying countless docker repos, this repo came as a great respite for me. However, upon trying docker-compose up, I got stuck with few minor issues and doubts.

Upon looking through the dockerfile of this project, I found that the startup entrypoint of the container run event is CMD ["pio"] which i guess was done to allow flexible command arguments passing on run. But, in docker CMD ["pio"] creates immutable entrypoint which doesn't allow any argument passing. For the flexibility of passing command line arguments on run, which what you might have actually intended, you need to use ENTRYPOINT ["pio"] instead of CMD ["pio"].  

Secondly, I was going through docker-compose file, and although, I am completely newbie in my understanding of docker-compose , but i guess it is somewhat similar to kubernetes pods. It seems in docker compose, by default, you opened the port 7070 for event server, 9000 for dashboard, but you forgot to open port 8000 on which engine will be deployed by default. As per command config of docker-compose file is concerned, documentation suggests that it overrides the default docker command. As of now, it is putting predictionio container to infinite sleep. 

But, what we really want is ability to start, train, and deploy the composed container system created. I am clueless about how to carry those typical lifecycle tasks once the pio is started. Although, i did managed to properly boot up the event server by modifying the docker-compose command file to :  
    
command:
    - /bin/bash
    - pio
    - eventserver
  
And, after i ssh'ed into the predictionio docker container after running the modified command i mentioned above and checked pio status, everything was running fine. But, when i tried to train using 'pio train', I am getting following error:

pio train
[WARN] [WorkflowUtils$] Environment variable POSTGRES_JDBC_DRIVER is pointing to a nonexistent file /home/pio/lib/postgresql-42.2.0.jar. Ignoring.
[INFO] [Runner$] Submission command: /home/pio/vendors/spark-2.1.1-bin-hadoop2.6/bin/spark-submit --class org.apache.predictionio.workflow.CreateWorkflow --jars file:/home/pio/app/lib/universal-recommender_2.11-0.7.3.jar,file:/home/pio/app/lib/universal-recommender-assembly-0.7.3-deps.jar,file:/home/pio/lib/spark/pio-data-hdfs-assembly-0.12.1.jar,file:/home/pio/lib/spark/pio-data-elasticsearch-assembly-0.12.1.jar,file:/home/pio/lib/spark/pio-data-localfs-assembly-0.12.1.jar,file:/home/pio/lib/spark/pio-data-hbase-assembly-0.12.1.jar,file:/home/pio/lib/spark/postgresql-42.2.0.jar,file:/home/pio/lib/spark/pio-data-jdbc-assembly-0.12.1.jar,file:/home/pio/lib/spark/pio-data-s3-assembly-0.12.1.jar --files file:/home/pio/conf/log4j.properties --driver-class-path /home/pio/conf:/home/pio/lib/postgresql-42.2.0.jar --driver-java-options -Dpio.log.dir=/home/pio file:/home/pio/lib/pio-assembly-0.12.1.jar --engine-id com.actionml.RecommendationEngine --engine-version da5c765435adbd8d2010cf07337422fdd38b20dd --engine-variant file:/home/pio/app/engine.json --verbosity 0 --json-extractor Both --env PIO_ENV_LOADED=1,PIO_STORAGE_REPOSITORIES_METADATA_NAME=pio_meta,PIO_VERSION=0.12.1,PIO_FS_BASEDIR=/home/pio/.pio_store,PIO_STORAGE_SOURCES_ELASTICSEARCH_HOSTS=elasticsearch,PIO_HOME=/home/pio,PIO_FS_ENGINESDIR=/home/pio/.pio_store/engines,PIO_DB_USER=pio,PIO_STORAGE_SOURCES_PGSQL_URL=jdbc:postgresql://postgres/pio,PIO_STORAGE_SOURCES_ELASTICSEARCH_TYPE=elasticsearch,PIO_STORAGE_REPOSITORIES_METADATA_SOURCE=PGSQL,PIO_DB=pio,PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE=PGSQL,PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME=pio_event,PIO_DB_HOST=postgres,PIO_STORAGE_SOURCES_PGSQL_PASSWORD=pio,PIO_STORAGE_SOURCES_PGSQL_TYPE=jdbc,PIO_FS_TMPDIR=/home/pio/.pio_store/tmp,PIO_STORAGE_SOURCES_PGSQL_USERNAME=pio,PIO_STORAGE_REPOSITORIES_MODELDATA_NAME=pio_model,PIO_STORAGE_SOURCES_ELASTICSEARCH_SCHEMES=http,PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE=PGSQL,PIO_CONF_DIR=/home/pio/conf,PIO_STORAGE_SOURCES_ELASTICSEARCH_PORTS=9200,PIO_DB_PASSWORD=pio
[INFO] [RecommendationEngine$]

               _   _             __  __ _
     /\       | | (_)           |  \/  | |
    /  \   ___| |_ _  ___  _ __ | \  / | |
   / /\ \ / __| __| |/ _ \| '_ \| |\/| | |
  / ____ \ (__| |_| | (_) | | | | |  | | |____
 /_/    \_\___|\__|_|\___/|_| |_|_|  |_|______|

[INFO] [Engine] Extracting datasource params...
[INFO] [WorkflowUtils$] No 'name' is found. Default empty String will be used.
[INFO] [Engine] Datasource params: (,DataSourceParams(handmade,List(purchase, view),None,None))
[INFO] [Engine] Extracting preparator params...
[INFO] [Engine] Preparator params: (,Empty)
[INFO] [Engine] Extracting serving params...
[INFO] [Engine] Serving params: (,Empty)
[INFO] [log] Logging initialized @10870ms
[INFO] [Server] jetty-9.2.z-SNAPSHOT
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@6cbbb9c4{/jobs,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@63f9b562{/jobs/json,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@20ead579{/jobs/job,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@5426cb36{/jobs/job/json,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@65e22def{/stages,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@4b1ec694{/stages/json,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@3d299393{/stages/stage,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@5f34907b{/stages/stage/json,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@2b4d4327{/stages/pool,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@16da1abc{/stages/pool/json,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@671ea6ff{/storage,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@1c52552f{/storage/json,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@5dc769f9{/storage/rdd,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@1b0e9707{/storage/rdd/json,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@9b5f3c7{/environment,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@74024f3{/environment/json,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@61ae0d43{/executors,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@ef718de{/executors/json,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@287ae90c{/executors/threadDump,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@2e1b374c{/executors/threadDump/json,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@3fcee3d9{/static,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@9c93d16{/,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@760487aa{/api,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@1526f71{/jobs/job/kill,null,AVAILABLE,@Spark}
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@49ca94a9{/stages/stage/kill,null,AVAILABLE,@Spark}
[INFO] [ServerConnector] Started Spark@343ce9f7{HTTP/1.1}{0.0.0.0:4040}
[INFO] [Server] Started @11325ms
[INFO] [ContextHandler] Started o.s.j.s.ServletContextHandler@2d7637e6{/metrics/json,null,AVAILABLE,@Spark}
[INFO] [DataSource]
??????????????????????????????????????????????????????????????
? Init DataSource                                            ?
? ?????????????????????????????????????????????????????????? ?
? App name                      handmade                     ?
? Event window                  None                         ?
? Event names                   List(purchase, view)         ?
? Min events per user           None                         ?
??????????????????????????????????????????????????????????????

[INFO] [URAlgorithm]
??????????????????????????????????????????????????????????????
? Init URAlgorithm                                           ?
? ?????????????????????????????????????????????????????????? ?
? App name                      handmade                     ?
? ES index name                 urindex                      ?
? ES type name                  items                        ?
? RecsModel                     all                          ?
? Event names                   List(purchase, view)         ?
? ?????????????????????????????????????????????????????????? ?
? Random seed                   -1446007577                  ?
? MaxCorrelatorsPerEventType    50                           ?
? MaxEventsPerEventType         500                          ?
? BlacklistEvents               List(purchase)               ?
? ?????????????????????????????????????????????????????????? ?
? User bias                     1.0                          ?
? Item bias                     1.0                          ?
? Max query events              100                          ?
? Limit                         20                           ?
? ?????????????????????????????????????????????????????????? ?
? Rankings:                                                  ?
? popular                       Some(popRank)                ?
??????????????????????????????????????????????????????????????

[INFO] [Engine$] EngineWorkflow.train
[INFO] [Engine$] DataSource: com.actionml.DataSource@61149fa5
[INFO] [Engine$] Preparator: com.actionml.Preparator@1a2e0d57
[INFO] [Engine$] AlgorithmList: List(com.actionml.URAlgorithm@739e8b96)
[INFO] [Engine$] Data sanity check is on.
[ERROR] [Common$] Invalid app name handmade
[INFO] [ServerConnector] Stopped Spark@343ce9f7{HTTP/1.1}{0.0.0.0:4040}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@49ca94a9{/stages/stage/kill,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@1526f71{/jobs/job/kill,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@760487aa{/api,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@9c93d16{/,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@3fcee3d9{/static,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@2e1b374c{/executors/threadDump/json,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@287ae90c{/executors/threadDump,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@ef718de{/executors/json,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@61ae0d43{/executors,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@74024f3{/environment/json,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@9b5f3c7{/environment,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@1b0e9707{/storage/rdd/json,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@5dc769f9{/storage/rdd,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@1c52552f{/storage/json,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@671ea6ff{/storage,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@16da1abc{/stages/pool/json,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@2b4d4327{/stages/pool,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@5f34907b{/stages/stage/json,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@3d299393{/stages/stage,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@4b1ec694{/stages/json,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@65e22def{/stages,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@5426cb36{/jobs/job/json,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@20ead579{/jobs/job,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@63f9b562{/jobs/json,null,UNAVAILABLE,@Spark}
[INFO] [ContextHandler] Stopped o.s.j.s.ServletContextHandler@6cbbb9c4{/jobs,null,UNAVAILABLE,@Spark}
Exception in thread "main" java.lang.IllegalArgumentException: Invalid app name handmade
        at org.apache.predictionio.data.store.Common$$anonfun$appNameToId$1$$anonfun$apply$3.apply(Common.scala:56)
        at org.apache.predictionio.data.store.Common$$anonfun$appNameToId$1$$anonfun$apply$3.apply(Common.scala:54)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.predictionio.data.store.Common$$anonfun$appNameToId$1.apply(Common.scala:54)
        at org.apache.predictionio.data.store.Common$$anonfun$appNameToId$1.apply(Common.scala:36)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
        at org.apache.predictionio.data.store.Common$.appNameToId(Common.scala:36)
        at org.apache.predictionio.data.store.PEventStore$.find(PEventStore.scala:71)
        at com.actionml.DataSource.readTraining(DataSource.scala:76)
        at com.actionml.DataSource.readTraining(DataSource.scala:48)
        at org.apache.predictionio.controller.PDataSource.readTrainingBase(PDataSource.scala:40)
        at org.apache.predictionio.controller.Engine$.train(Engine.scala:642)
        at org.apache.predictionio.controller.Engine.train(Engine.scala:176)
        at org.apache.predictionio.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:67)
        at org.apache.predictionio.workflow.CreateWorkflow$.main(CreateWorkflow.scala:251)
        at org.apache.predictionio.workflow.CreateWorkflow.main(CreateWorkflow.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Consequently, pio deploy is also not working.

pio@9ade508038c0:~/app$ pio deploy
[ERROR] [Engine$] No valid engine instance found for engine com.actionml.RecommendationEngine da5c765435adbd8d2010cf07337422fdd38b20dd.
Try running 'train' before 'deploy'. Aborting.

Would it be possible to boot directly a new detached terminal session to predictionio container automatically after docker-compose up, while elasticsearch and postgres output keep showing on the original terminal instance?   
Also, how can universal recommender pio train error & subsequently deploy error can be fixed?

**Comment by prateekrastogi** [comment]
Hi,

Finally, managed to get the pretty good overview about how to use your project and  understood that you simply choose to build directly from the source and skip integration test run as suggested on actionml docs altogether to save space and installs. Although, I will need some time to develop a proper data model to feed into the system and cross-check that everything is working as intended. In the meantime, I will update the readme and create a pull request to help the newbies like me hopping from one repo to another in search of your repo :-). As of now, I am closing the issue, will open new one in future if some unsolvable problem arises somewhere while actually integrating it with my application.
